AIRPORTS = [
    {
        "name": "Coimbatore International Airport",
        "city": "Coimbatore",
        "country": "India",
        "iata": "CJB",
        "icao": "VOCB",
    },
    {
        "name": "Chennai International Airport",
        "city": "Chennai",
        "country": "India",
        "iata": "MAA",
        "icao": "VOMM",
    },
    {
        "name": "Kempegowda International Airport",
        "city": "Bengaluru",
        "country": "India",
        "iata": "BLR",
        "icao": "VOBL",
    },
    {
        "name": "Chhatrapati Shivaji Maharaj International Airport",
        "city": "Mumbai",
        "country": "India",
        "iata": "BOM",
        "icao": "VABB",
    },
    {
        "name": "Indira Gandhi International Airport",
        "city": "Delhi",
        "country": "India",
        "iata": "DEL",
        "icao": "VIDP",
    },
    {
        "name": "Rajiv Gandhi International Airport",
        "city": "Hyderabad",
        "country": "India",
        "iata": "HYD",
        "icao": "VOHS",
    },
    {
        "name": "Cochin International Airport",
        "city": "Kochi",
        "country": "India",
        "iata": "COK",
        "icao": "VOCI",
    },
    {
        "name": "Pune International Airport",
        "city": "Pune",
        "country": "India",
        "iata": "PNQ",
        "icao": "VAPO",
    },
    {
        "name": "Goa International Airport",
        "city": "Goa",
        "country": "India",
        "iata": "GOI",
        "icao": "VOGO",
    },
    {
        "name": "Netaji Subhas Chandra Bose International Airport",
        "city": "Kolkata",
        "country": "India",
        "iata": "CCU",
        "icao": "VECC",
    },
    {
        "name": "Singapore Changi Airport",
        "city": "Singapore",
        "country": "Singapore",
        "iata": "SIN",
        "icao": "WSSS",
    },
    {
        "name": "Heathrow Airport",
        "city": "London",
        "country": "United Kingdom",
        "iata": "LHR",
        "icao": "EGLL",
    },
    {
        "name": "Dubai International Airport",
        "city": "Dubai",
        "country": "United Arab Emirates",
        "iata": "DXB",
        "icao": "OMDB",
    },
    {
        "name": "Hamad International Airport",
        "city": "Doha",
        "country": "Qatar",
        "iata": "DOH",
        "icao": "OTHH",
    },
    {
        "name": "John F. Kennedy International Airport",
        "city": "New York",
        "country": "United States",
        "iata": "JFK",
        "icao": "KJFK",
    },
    {
        "name": "Los Angeles International Airport",
        "city": "Los Angeles",
        "country": "United States",
        "iata": "LAX",
        "icao": "KLAX",
    },
    {
        "name": "San Francisco International Airport",
        "city": "San Francisco",
        "country": "United States",
        "iata": "SFO",
        "icao": "KSFO",
    },
    {
        "name": "Sydney Kingsford Smith Airport",
        "city": "Sydney",
        "country": "Australia",
        "iata": "SYD",
        "icao": "YSSY",
    },
    {
        "name": "Tokyo Haneda Airport",
        "city": "Tokyo",
        "country": "Japan",
        "iata": "HND",
        "icao": "RJTT",
    },
    {
        "name": "Frankfurt Airport",
        "city": "Frankfurt",
        "country": "Germany",
        "iata": "FRA",
        "icao": "EDDF",
    },
    {
        "name": "Paris Charles de Gaulle Airport",
        "city": "Paris",
        "country": "France",
        "iata": "CDG",
        "icao": "LFPG",
    },
]
